version: "3.9"

services:
  client:
    container_name: client
    build:
      context: ./client
    ports:
      - 3000:3000
    networks:
      - blog-network
  event-bus:
    container_name: event-bus
    build:
      context: ./event-bus
    ports:
      - 4005:4005
    networks:
      - blog-network
  query-service:
    container_name: query-service
    build:
      context: ./query-service
    ports:
      - 4002:4002
    networks:
      - blog-network
  posts-service:
    container_name: posts-service
    build:
      context: ./posts-service
    ports:
      - 4000:4000
    networks:
      - blog-network
  moderation-service:
    container_name: moderation-service
    build:
      context: ./moderation-service
    ports:
      - 4003:4003
    networks:
      - blog-network
  comments-service:
    container_name: comments-service
    build:
      context: ./comments-service
    ports:
      - 4001:4001
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
